### ISSUE TITLE
Add admin helper

### ISSUE THREAD

**Issue by PierreRambaud** [GotCms/GotCms#127]
Add admin helper to retrieve admin authentication in frontend / backend.

Example:

`$this->admin()` can return false or instance of Gc\User\Model;

```
if ($this->admin()) {
    $this->admin()->getName();
}
```

**Comment by kienle83** [comment]
Bonjour Pierrer

I had a problem with login. By method authenticate in  Model of User (https://github.com/GotCms/GotCms/blob/master/library/Gc/User/Model.php):

 if ($result->isValid()) {
$data = $authAdapter->getResultRowObject(null, 'password');
$this->setData((array) $data);
$this->setOrigData();
$auth->getStorage()->write($this);
$this->events()->trigger(__CLASS__, 'after.auth', $this);
return true;
}

$result is valid, method returns "true". But in Controller: $auth = $this->getServiceLocator()->get('Auth') returns false. 

I think that error happen at line 90 of user model ($auth->getStorage()->write($this);), at this position model can be not saved into $auth.

Or error happen at line 72 of module.cofig.php (https://github.com/GotCms/GotCms/blob/master/module/GcFrontend/config/module.config.php): 
return new AuthenticationService(new Storage\Session(UserModel::BACKEND_AUTH_NAMESPACE));

What do you think about this problem? Maybe because of session too?
