### ISSUE TITLE
jQueryFileUpload - image upload error

### ISSUE THREAD

**Issue by jakub023** [GotCms/GotCms#276]
Hi,
I try upload image using jQueryFileUpload. 
If I select image and try upload it, shows this JS error:
```
TypeError: that is undefined
options = that.options,
File: /backend/assets/datatypes/jqueryfileupload/jquery.fileupload-ui.js (line 88, col 20)
```
Browser: Firefox 34.0
GotCms version: 1.5.1

Can someone help me?
Thanks

**Comment by PierreRambaud** [comment]
Hi,
I will have a look tomorrow, otherwise, if you find a solution, I will be glad to merge your pull request ;)

Regards

**Comment by PierreRambaud** [comment]
Hi again and sorry for the delay,
I tried some things but I found bugs after updating the jqueryfileupload datatype.
I'm no longer a php developper and don't really follow the development of javascript or ZendFramework.
If you have a fix you can purpose a pull request, otherwise, it not will be fix now and I suggest you to use the simple upload datatype :/

Sorry
