### ISSUE TITLE
Some help to work with GotCms

### ISSUE THREAD

**Issue by hpbrasileliro** [GotCms/GotCms#278]
Dear Pierre Rambaud

I would be grateful if you could help me how to think.
I am using Ubuntu 12.4, php 5.5.21 and MySql

After the instalation, I had some dificulties to understand how to think to create a simple page and get the answer in frontend.

If you have a demo with fonts and inserts, just a simple site, a menu and two pages, will you help-me a lot.

Yours sincerely,

**Comment by PierreRambaud** [comment]
Hi,

Logically when you install the CMS, you choose between three little themes. With that, you can views some information in `document type`, `layout`, `view`, and `script` that allow you to easly understand how it works.
Otherwise for theming you can view them in `data/install/design`, after a `document type` must contain the right information to make it work.
I hope I helped.

Regards
