### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by e-v-medvedev** [GotCms/GotCms#287]
Who $this->layout()->moduleMenu value forms? I created module "namespace/modulename" in /module  directory. My module can`t find modulename-gc.phtml file.

**Comment by PierreRambaud** [comment]
Hi,
If you want to create a custom module you must add it in `extensions/ZfModules` if it's backend module add it in `extensions/Modules`.
And this variable is assign here: https://github.com/GotCms/GotCms/blob/e3f3246dc260165d59d511aab4308df02a1ba2f1/module/GcModule/Module.php#L110

Regards

**Comment by e-v-medvedev** [comment]
If i put module if zfModule/<namespace> gotcms try to load <namespace> as module. It`s not acceptable. I need create my own namespace folde with modules in sunfolders. In case of placing my own modules in /module, i am sure, that they also will work with other ZF applcation as well.
And thanks for your answer :-).

**Comment by PierreRambaud** [comment]
That the aim of `extensions/ZfModules` directory, they are automatically loaded by `config/application.php` otherwise you must edit this file to load your module.
More, `$this->layout()->moduleMenu` is a variable for `Backend module`, that are in `library/Modules` or `extensions/Modules`. They can't works exactly as ZfModules due to GotCms dependencies.

**Comment by e-v-medvedev** [comment]
According to your words there must not be difference between /module and /extensions/ZfModules but my modules works fine in /module folder and not works being in /extensions/ZfModules. I tried to move my working modules from /module to /extensions/ZfModules and got an error.

**Comment by e-v-medvedev** [comment]
In config/application.php my modules added like 'namespace\modulename'. Am i wrong?

**Comment by PierreRambaud** [comment]
Yes, it's useless to add it when you add your module in extensions directory because it's automatically loaded here: https://github.com/GotCms/GotCms/blob/master/config/application.config.php#L38
Backend modules are loaded by installing them with the Cms (modules part).
What do you want to do exactly? Creating a Zend framework module, or creating a module for GotCms?

**Comment by e-v-medvedev** [comment]
I am creating a platform for deloping corporative applications. First of all, i try to write some modules and first of them is module "Customer" which i placed in /module/Smartceo folder (there are some other modules in it). This module allow to manage customers (or employes) and there access rights. Today i was writing backend interface for add, delete and update customers. I wanted my interface looks like default GotCMS admin interface. All at all i did it, but in ugly way. I instantiated my controller from Gc\Mvc\Controller\Action not from Gc\Mvc\Controller\AbstractController and add sidebar menu in ZF usual way. May be it is not the best way, but for a couple of days without documentation that`s all i could do :-).

**Comment by PierreRambaud** [comment]
No sure it's a bad idea if you need modules also works for other ZF2 applications. But instead of putting them into `modules`, you must put them into `extensions/ZfModules`, otherwise you will not be able to update the cms due to conflicts error (using git).

**Comment by e-v-medvedev** [comment]
Ok.

**Comment by PierreRambaud** [comment]
Don't hesitate to open a new issue if you have new questions ;)
